spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jackson:
    deserialization:
      fail_on_unknown_properties: true
  datasource:
    username: postgres
    password: 3621
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        security: DEBUG
my-app:
  clientId: myApp
  clientSecret: pass
