spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jackson:
    deserialization:
      fail_on_unknown_properties: true
